<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZf3x5js\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZf3x5js/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZf3x5js.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZf3x5js\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZf3x5js\appProdProjectContainer(array(
    'container.build_hash' => 'Zf3x5js',
    'container.build_id' => '74548fb9',
    'container.build_time' => 1518771028,
));
