<?php

namespace Proxies\__CG__\BackBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parameters extends \BackBundle\Entity\Parameters implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'applicationNale', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'logo', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'adress', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'adress2', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'phoneNumber', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'fax', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'emailRequest'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'id', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'applicationNale', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'logo', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'adress', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'adress2', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'phoneNumber', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'fax', '' . "\0" . 'BackBundle\\Entity\\Parameters' . "\0" . 'emailRequest'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parameters $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApplicationNale($applicationNale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplicationNale', [$applicationNale]);

        return parent::setApplicationNale($applicationNale);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicationNale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicationNale', []);

        return parent::getApplicationNale();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress($adress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress2($adress2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress2', [$adress2]);

        return parent::setAdress2($adress2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress2', []);

        return parent::getAdress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailRequest($emailRequest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailRequest', [$emailRequest]);

        return parent::setEmailRequest($emailRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailRequest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailRequest', []);

        return parent::getEmailRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setPonderationNote($ponderationNote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPonderationNote', [$ponderationNote]);

        return parent::setPonderationNote($ponderationNote);
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderationNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationNote', []);

        return parent::getPonderationNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setPonderationNoteMembers($ponderationNoteMembers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPonderationNoteMembers', [$ponderationNoteMembers]);

        return parent::setPonderationNoteMembers($ponderationNoteMembers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPonderationNoteMembers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPonderationNoteMembers', []);

        return parent::getPonderationNoteMembers();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfScreens($numberOfScreens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfScreens', [$numberOfScreens]);

        return parent::setNumberOfScreens($numberOfScreens);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfScreens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfScreens', []);

        return parent::getNumberOfScreens();
    }

    /**
     * {@inheritDoc}
     */
    public function setSizeMaxUpload($sizeMaxUpload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSizeMaxUpload', [$sizeMaxUpload]);

        return parent::setSizeMaxUpload($sizeMaxUpload);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizeMaxUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizeMaxUpload', []);

        return parent::getSizeMaxUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberMaxTags($numberMaxTags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberMaxTags', [$numberMaxTags]);

        return parent::setNumberMaxTags($numberMaxTags);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberMaxTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberMaxTags', []);

        return parent::getNumberMaxTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfStaff($numberOfStaff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfStaff', [$numberOfStaff]);

        return parent::setNumberOfStaff($numberOfStaff);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfStaff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfStaff', []);

        return parent::getNumberOfStaff();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevenue($revenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevenue', [$revenue]);

        return parent::setRevenue($revenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenue', []);

        return parent::getRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteType($websiteType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteType', [$websiteType]);

        return parent::setWebsiteType($websiteType);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteType', []);

        return parent::getWebsiteType();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarget($target)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarget', [$target]);

        return parent::setTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarget', []);

        return parent::getTarget();
    }

    /**
     * {@inheritDoc}
     */
    public function setGraphicalStyle($graphicalStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGraphicalStyle', [$graphicalStyle]);

        return parent::setGraphicalStyle($graphicalStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getGraphicalStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGraphicalStyle', []);

        return parent::getGraphicalStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBehavior($behavior)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBehavior', [$behavior]);

        return parent::setBehavior($behavior);
    }

    /**
     * {@inheritDoc}
     */
    public function getBehavior()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBehavior', []);

        return parent::getBehavior();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountries($countries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountries', [$countries]);

        return parent::setCountries($countries);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountries', []);

        return parent::getCountries();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguages($languages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguages', [$languages]);

        return parent::setLanguages($languages);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', []);

        return parent::getLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainColors($mainColors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainColors', [$mainColors]);

        return parent::setMainColors($mainColors);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainColors', []);

        return parent::getMainColors();
    }

    /**
     * {@inheritDoc}
     */
    public function setCms($cms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCms', [$cms]);

        return parent::setCms($cms);
    }

    /**
     * {@inheritDoc}
     */
    public function getCms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCms', []);

        return parent::getCms();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrameworks($frameworks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrameworks', [$frameworks]);

        return parent::setFrameworks($frameworks);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrameworks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrameworks', []);

        return parent::getFrameworks();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevLanguage($devLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevLanguage', [$devLanguage]);

        return parent::setDevLanguage($devLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevLanguage', []);

        return parent::getDevLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTechFront($techFront)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTechFront', [$techFront]);

        return parent::setTechFront($techFront);
    }

    /**
     * {@inheritDoc}
     */
    public function getTechFront()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTechFront', []);

        return parent::getTechFront();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissions($missions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissions', [$missions]);

        return parent::setMissions($missions);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissions', []);

        return parent::getMissions();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluations($evaluations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluations', [$evaluations]);

        return parent::setEvaluations($evaluations);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluations', []);

        return parent::getEvaluations();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessions($professions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessions', [$professions]);

        return parent::setProfessions($professions);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessions', []);

        return parent::getProfessions();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialNetworks($socialNetworks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialNetworks', [$socialNetworks]);

        return parent::setSocialNetworks($socialNetworks);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialNetworks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialNetworks', []);

        return parent::getSocialNetworks();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlogCategories($blogCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlogCategories', [$blogCategories]);

        return parent::setBlogCategories($blogCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlogCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlogCategories', []);

        return parent::getBlogCategories();
    }

}
