<?php

namespace BackBundle\Repository;

/**
 * CategoryAwardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAwardsRepository extends \Doctrine\ORM\EntityRepository
{
}
