<?php

namespace BackBundle\Repository;

/**
 * ColorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorsRepository extends \Doctrine\ORM\EntityRepository
{
}
