<?php

namespace BackBundle\Repository;

/**
 * ContestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestsRepository extends \Doctrine\ORM\EntityRepository
{
}
