<?php

namespace BackBundle\Repository;

/**
 * customerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customerRepository extends \Doctrine\ORM\EntityRepository
{
}
