<?php

namespace BackBundle\Repository;

/**
 * InfoCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
