<?php

namespace BackBundle\Repository;

/**
 * info3WAwardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class info3WAwardsRepository extends \Doctrine\ORM\EntityRepository
{
}
