<?php

namespace BackBundle\Repository;

/**
 * juryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class juryRepository extends \Doctrine\ORM\EntityRepository
{
}
