<?php

namespace BackBundle\Repository;

/**
 * parametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametersRepository extends \Doctrine\ORM\EntityRepository
{
}
