<?php

namespace BackBundle\Repository;

/**
 * projectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projectRepository extends \Doctrine\ORM\EntityRepository
{
}
