<?php

namespace BackBundle\Repository;

/**
 * TechnologiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologiesRepository extends \Doctrine\ORM\EntityRepository
{
}
