<?php

namespace BackBundle\Repository;

/**
 * TestFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestFormRepository extends \Doctrine\ORM\EntityRepository
{
}
