<?php

namespace BackBundle\Repository;

/**
 * WebsitesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsitesTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
