<?php

namespace BackBundle\Repository;

/**
 * WebsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
