<?php

namespace BackBundle\Repository;

/**
 * WebsiteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
