<?php

namespace BackBundle\Repository;

/**
 * WebsitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsitesRepository extends \Doctrine\ORM\EntityRepository
{
}
