<?php

namespace BackBundle\Repository;

/**
 * awardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwardsRepository extends \Doctrine\ORM\EntityRepository
{
}
