<?php

namespace BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllCategoriesWithRenameAttrObject()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c.id as id,c.itemName as itemName')
            ->from($this->_entityName, 'c');

        return $qb->getQuery()->getResult();
    }
}
