<?php

namespace BackBundle\Repository;

/**
 * VoteCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteCriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
