services:
    back.util.crud:
        class: BackBundle\Util\Crud
        arguments:
            - "@service_container"
    submit_listener:
        class: BackBundle\EventListener\SubmitListener
        tags:
          - { name: doctrine.event_listener , event: postPersist  }