<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVt10gkd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVt10gkd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVt10gkd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVt10gkd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVt10gkd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vt10gkd',
    'container.build_id' => 'edb1e739',
    'container.build_time' => 1518770838,
));
