<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'back.util.crud' shared service.

include_once $this->targetDirs[3].'\\src\\BackBundle\\Util\\Crud.php';

return $this->services['back.util.crud'] = new \BackBundle\Util\Crud($this);
