imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: config_easy_admin.yml }
    - { resource: "@BackBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.customer_images: uploads/images/customers
    app.path.agency_images: uploads/images/agency
    app.path.parameter_images: uploads/images/parameter
    app.path.project_images: uploads/images/website
    app.path.user_images: uploads/images/user
    gender: # params for easy admin
        M: M
        F: F

framework:
    serializer:
        enabled: true
    #esi: ~
    translator: { fallbacks: [ "fr" ] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: contact@3wawards.com
        sender_name: 3awards

fos_rest:
   body_converter:
       enabled: true
       validate: true
       validation_errors_argument: violations
   view:
       formats: { json: true, xml: false, rss: false }
       view_response_listener: true
   serializer:
       serialize_null: true
   format_listener:
       rules:
           - { path: '^/administration/api', priorities: ['json'], fallback_format: 'json' }
           - { path: '^/login', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
           - { path: '^/admin', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
           - { path: '^/api/login_check', priorities: ['json'], fallback_format: 'json' }
           - { path: '^/3w_awards/back/web/uploads/images/user', priorities: [ 'text/html', '*/*'], prefer_extension: true }


# disable @View  of SensioFrameworkExtraBundle
sensio_framework_extra:
    view: { annotations: true }
    request: { converters: true }

# image upload
vich_uploader:
    db_driver: orm
    mappings:
        customer_images:
            uri_prefix: '%app.path.customer_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/customers'
        agency_images:
            uri_prefix: '%app.path.agency_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/agency'
        parameter_images:
            uri_prefix: '%app.path.parameter_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/parameter'
        user_images:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/user'
        project_images:
            uri_prefix: '%app.path.project_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/website'



lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        3600
    user_identity_field: username

    # token encoding/decoding settings
    encoder:
        # token encoder/decoder service - default implementation based on the namshi/jose library
        service:            lexik_jwt_authentication.encoder.default
        # crypto engine used by the encoder service
        crypto_engine:  openssl
        # encryption algorithm used by the encoder service
        signature_algorithm: RS256

    # token extraction settings
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:                    # check token in a cookie
            enabled: false
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: false
            name:    bearer

nelmio_cors:
    defaults:
    paths:
        '/administration/api':
              allow_origin: ['*']
              allow_headers: [ 'content-type', 'authorization']
              allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
              max_age: 3600

nelmio_api_doc: ~

jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                path: "@UserBundle/Resources/config/serializer/"
                namespace_prefix: "FOS\\UserBundle"


vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/assets/upload'

parameters:

