imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BackBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.customer_images: uploads/images/customers

framework:
    serializer:
        enabled: true
    #esi: ~
    translator: { fallbacks: [ "fr" ] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: contact@3wawards.com
        sender_name: 3awards

fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true

# disable @View  of SensioFrameworkExtraBundle
sensio_framework_extra:
    view: { annotations: true }
    request: { converters: true }

# image upload
vich_uploader:
    db_driver: orm
    mappings:
        customer_images:
            uri_prefix: '%app.path.customer_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/customers'

# app/config/config.yml
easy_admin:
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '', title: "Edit"}
            - { name: 'delete', icon: 'trash', label: '', title: "Delete"}
    entities:
        Agency:
            class:  BackBundle\Entity\Agency
            list:
                title: "Les Agences"
                actions:
                    - { name: 'new', label: 'Ajouter une Agence' }
        Awards:
            class: BackBundle\Entity\Awards
            list:
                title: "Les Prix"
                actions:
                    - { name: 'new', label: 'Ajouter un Prix' }
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'categoryAwards', label: 'Catégorie'}
                    - { property: 'project', label: 'Projet'}
            form:
                title: "Ajouter un Prix"
                fields:
                   - { property: 'name', label: 'Nom'}
                   - { property: 'categoryAwards', label: 'Catégorie'}
                   - { property: 'project', label: 'Projet'}
        Blog:
            class: BackBundle\Entity\Blog
            list:
                title: "Les Blogs"
                actions:
                    - { name: 'new', label: 'Ajouter un Blog' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'articleTitle', label: 'Titre'}
                    - { property: 'status', label: 'Status', type: 'boolean'}
                    - { property: 'publicationDate', label: 'Date de publication', type: 'date'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'category', label: 'Catégorie'}
            form:
                    title: "Ajouter un article"
                    fields:
                        - { type: 'group', css_class: 'col-sm-9', label: 'Article', icon: 'pencil' }
                        - { property: 'articleTitle', label: 'Titre'}
                        - { property: 'resume', label: 'Résumé', type: 'ckeditor'}
                        - { property: 'description', label: 'Article', type: 'ckeditor'}
                        - { type: 'group', css_class: 'col-sm-3', label: 'Détails', icon: 'search' }
                        - { property: 'status', label: 'Status'}
                        - { property: 'publicationDate', label: 'Date de publication', type: 'date'}
                        - { property: 'category', label: 'Catégorie'}
        CategoryAwards:
            class: BackBundle\Entity\CategoryAwards
            list:
                title: "Les Catégories de Prix"
                fields:
                     - { property: 'label', label: 'Libelle'}
                actions:
                    - { name: 'new', label: 'Ajouter une Catégorie' }
            form:
                title: "Ajouter une catégorie de prix"
                fields:
                    - { property: 'label', label: 'Titre', css_class: 'col-sm-4'}
        Customer:
            class: BackBundle\Entity\Customer
            list:
                title: "Les Clients"
                actions:
                    - { name: 'new', label: 'Ajouter un Client' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'image', label: 'Logo', type: 'image', base_path: '%app.path.customer_images%' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'categories', label: 'Catégorie'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'agency', label: 'Agence'}
            form:
                title: "Ajouter un client"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Détails du client', icon: 'user' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'website', label: 'Site internet', type: 'url'}
                    - { property: 'categories', label: 'Catégorie'}
                    - { property: 'categoryAwards', label: 'Catégories de Prix'}
                    - { property: 'imageFile', label: 'Logo', type: 'vich_image', }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact', icon: 'map-marker' }
                    - { property: 'adress', label: 'Adresse'}
                    - { property: 'adress2', label: 'Adresse 2'}
                    - { property: 'postalCode', label: 'Code Postal'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'phoneNumber', label: 'Numéro de Téléphone'}
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations complémentaire', icon: 'pencil' }
                    - { property: 'presentation', label: 'Présentation', type: 'ckeditor'}
                    - { property: 'expertise', label: 'Expertise'}
                    - { property: 'notes', label: 'Notes', type: 'ckeditor'}
                    - { property: 'creationDate', label: 'Date de création', type: 'date'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Chiffres clés', icon: 'minus-square' }
                    - { property: 'staffNumber', label: 'Nombres de salarié'}
                    - { property: 'revenue', label: 'Chiffre d affaire', type: 'money', type_options: { currency: 'EUR' }}
                    - { property: 'tvaNumber', label: 'Numéro de TVA'}
                    - { property: 'numeroDuns', label: 'numéroDuns?'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres', icon: 'mobile' }
                    - { property: 'admin', label: 'Admin'}
#                    - { property: 'agency', label: 'Agence'}
                    - { property: 'fax', label: 'Fax'}
        Parameters:
            class: BackBundle\Entity\Parameters
            list:
                title: "Les Paramètres"
                actions:
                    - { name: 'new', label: 'Ajouter un Paramètre' }
        Project:
            class: BackBundle\Entity\Project
            list:
                title: "Les projets"
                actions:
                    - { name: 'new', label: 'Ajouter un Projet' }
    site_name: '<img src="https://i.imgur.com/vawr75B.png" />'
    design:
        form_theme: 'vertical'
        brand_color: 'grey'
        color_scheme: 'light'
        assets:
            favicon: '../docs/favicon.png'
        menu:
            - { entity: 'Project', label: 'Projet', icon: 'suitcase'}
            - { entity: 'Agency', label: 'Agences', icon: 'anchor'}
            - { entity: 'Blog', label: 'Blog', icon: 'pencil'}
            - { entity: 'Customer', label: 'Clients', icon: 'address-book'}
            - label: 'Les Prix'
            - { entity: 'Awards', label: 'Prix', icon: 'trophy'}
            - { entity: 'CategoryAwards', label: 'Catégorie de Prix', icon: 'certificate'}
            - label: 'Outils'
            - { entity: 'Parameter', label: 'Paramètres', icon: 'cog'}

lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        3600

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_headers: ['origin', 'content-type', 'authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
