easy_admin:
    site_name: '3w Awards'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '', title: "Edit"}
            - { name: 'delete', icon: 'trash', label: '', title: "Delete"}
    entities:
        Agency:
            class:  BackBundle\Entity\Agency
            list:
                title: "Les Agences"
                actions:
                    - { name: 'new', label: 'Ajouter une Agence' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'image', label: 'Logo', type: 'image', base_path: '%app.path.agency_images%' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'customer', label: 'Client'}
            form:
                title: "Ajouter une Agences"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Détails de l''''agence', icon: 'user' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'website', label: 'Site internet', type: 'url'}
                    - { property: 'project', label: ' Sites'}
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'imageFile', label: 'Logo', type: 'vich_image', }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact', icon: 'map-marker' }
                    - { property: 'adress', label: 'Adresse'}
                    - { property: 'adress2', label: 'Adresse 2'}
                    - { property: 'postalCode', label: 'Code Postal'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'phoneNumber', label: 'Numéro de Téléphone'}
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations complémentaire', icon: 'pencil' }
                    - { property: 'presentation', label: 'Présentation', type: 'ckeditor'}
                    - { property: 'expertise', label: 'Expertise'}
                    - { property: 'notes', label: 'Notes', type: 'ckeditor'}
                    - { property: 'creationDate', label: 'Date de création', type: 'date'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Chiffres clés', icon: 'minus-square' }
                    - { property: 'staffNumber', label: 'Nombres de salarié'}
                    - { property: 'revenue', label: 'Chiffre d affaire', type: 'money', type_options: { currency: 'EUR' }}
                    - { property: 'tvaNumber', label: 'Numéro de TVA'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres', icon: 'mobile' }
                    - { property: 'customer', label: 'Client'}
                    - { property: 'fax', label: 'Fax'}
        Awards:
            class: BackBundle\Entity\Awards
            list:
                title: "Les Prix"
                actions:
                    - { name: 'new', label: 'Ajouter un Prix' }
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'categoryAwards', label: 'Catégorie'}
                    - { property: 'project', label: 'Projet'}
            form:
                title: "Ajouter un Prix"
                fields:
                   - { property: 'name', label: 'Nom'}
                   - { property: 'categoryAwards', label: 'Catégorie'}
                   - { property: 'project', label: 'Projet'}
        Blog:
            class: BackBundle\Entity\Blog
            list:
                title: "Les Blogs"
                actions:
                    - { name: 'new', label: 'Ajouter un Blog' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'articleTitle', label: 'Titre'}
                    - { property: 'status', label: 'Status', type: 'boolean'}
                    - { property: 'publicationDate', label: 'Date de publication', type: 'date'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'category', label: 'Catégorie'}
            form:
                    title: "Ajouter un article"
                    fields:
                        - { type: 'group', css_class: 'col-sm-9', label: 'Article', icon: 'pencil' }
                        - { property: 'articleTitle', label: 'Titre'}
                        - { property: 'resume', label: 'Résumé', type: 'ckeditor'}
                        - { property: 'description', label: 'Article', type: 'ckeditor'}
                        - { type: 'group', css_class: 'col-sm-3', label: 'Détails', icon: 'search' }
                        - { property: 'status', label: 'Status'}
                        - { property: 'publicationDate', label: 'Date de publication', type: 'date'}
                        - { property: 'category', label: 'Catégorie'}
        CategoryAwards:
            class: BackBundle\Entity\CategoryAwards
            list:
                title: "Les Catégories de Prix"
                fields:
                     - { property: 'label', label: 'Libelle'}
                actions:
                    - { name: 'new', label: 'Ajouter une Catégorie' }
            form:
                title: "Ajouter une catégorie de prix"
                fields:
                    - { property: 'label', label: 'Titre', css_class: 'col-sm-4'}
        Customer:
            class: BackBundle\Entity\Customer
            list:
                title: "Les Clients"
                actions:
                    - { name: 'new', label: 'Ajouter un Client' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'image', label: 'Logo', type: 'image', base_path: '%app.path.customer_images%' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'agency', label: 'Agence'}
            form:
                title: "Ajouter un client"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Détails du client', icon: 'user' }
                    - { property: 'name', label: 'Nom'}
                    - { property: 'type', label: 'Type'}
                    - { property: 'website', label: 'Site internet', type: 'url'}
                    - { property: 'category', label: 'Catégorie'}
                    - { property: 'categoryAwards', label: 'Catégories de Prix'}
                    - { property: 'imageFile', label: 'Logo', type: 'vich_image', }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact', icon: 'map-marker' }
                    - { property: 'adress', label: 'Adresse'}
                    - { property: 'adress2', label: 'Adresse 2'}
                    - { property: 'postalCode', label: 'Code Postal'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'country', label: 'Pays'}
                    - { property: 'phoneNumber', label: 'Numéro de Téléphone'}
                    - { type: 'group', css_class: 'col-sm-12', label: 'Informations complémentaire', icon: 'pencil' }
                    - { property: 'presentation', label: 'Présentation', type: 'ckeditor'}
                    - { property: 'expertise', label: 'Expertise'}
                    - { property: 'notes', label: 'Notes', type: 'ckeditor'}
                    - { property: 'creationDate', label: 'Date de création', type: 'date'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Chiffres clés', icon: 'minus-square' }
                    - { property: 'staffNumber', label: 'Nombres de salarié'}
                    - { property: 'revenue', label: 'Chiffre d affaire', type: 'money', type_options: { currency: 'EUR' }}
                    - { property: 'tvaNumber', label: 'Numéro de TVA'}
                    - { property: 'numeroDuns', label: 'numéroDuns?'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Autres', icon: 'mobile' }
                    - { property: 'admin', label: 'Admin'}
#                    - { property: 'agency', label: 'Agence'}
                    - { property: 'fax', label: 'Fax'}
        Parameter:
            class: BackBundle\Entity\Parameter
            list:
                title: "Les Paramètres"
                actions:
                    - { name: 'new', label: 'Ajouter un Paramètre' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'image', label: 'Logo', type: 'image', base_path: '%app.path.parameter_images%' }
                    - { property: 'applicationNale', label: 'Nom'}
            form:
                title: "Ajouter un paramètre"
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Détails du client', icon: 'user' }
                    - { property: 'applicationNale', label: 'Nom'}
                    - { property: 'imageFile', label: 'Logo', type: 'vich_image', }
                    - { property: 'updatedAt', label: 'Mise à jour le:', type: 'date'}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Contact', icon: 'map-marker' }
                    - { property: 'adress', label: 'Adresse'}
                    - { property: 'adress2', label: 'Adresse 2'}
                    - { property: 'phoneNumber', label: 'Numéro de Téléphone'}
                    - { property: 'fax', label: 'Fax'}
                    - { property: 'emailRequest', label: 'Email', type: 'email'}
        Project:
            class: BackBundle\Entity\Project
            list:
                title: "Les projets"
                actions:
                    - { name: 'new', label: 'Ajouter un Projet' }
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'projectName', label: 'Nom'}
                    - { property: 'customer', label: 'Client'}
                    - { property: 'websiteType', label: 'Type'}
                    - { property: 'image', label: 'Screenshot', type: 'image', base_path: '%%app.path.project_images%' }
                    - { property: 'screenshot', label: 'Screenshot2', type: 'image', base_path: '%app.path.project_images%' }
                    - { property: 'second', label: 'Screenshot3', type: 'image', base_path: '%app.path.project_images%' }
            form:
                title: "Ajouter un project"
                fields:
                    - { type: 'group', css_class: 'col-sm-9', label: 'Détails du projet', icon: 'pencil' }
                    - { property: 'projectName', label: 'Nom'}
                    - { property: 'projectDescription', label: 'Présentation', type: 'ckeditor'}
                    - { property: 'imageFile', label: 'Image Principale', type: 'vich_image'}
                    - { property: 'screenshotFile', label: 'screenshot', type: 'vich_image'}
                    - { property: 'keywords', label: 'Mots Clés'}
                    - { property: 'websiteType', label: 'Type'}
                    - { property: 'activityArea', label: 'Activités'}
                    - { property: 'target', label: 'Cible'}
                    - { property: 'projectBudget', label: 'Budget'}
                    - { property: 'projectFocus', label: 'Focus'}
                    - { property: 'languages', label: 'Langues'}
                    - { property: 'createdBy', label: 'Crée par'}
                    - { property: 'clientName', label: 'Nom du client'}
                    - { property: 'releaseDate', label: 'Date de release', type: 'date'}
                    - { property: 'givingToAgency', label: 'Given to agency'}
                    - { property: 'keyFunctionnality', label: 'Fonctionnalité clé'}
                    - { property: 'techFront', label: 'Technos'}
                    - { property: 'devLanguages', label: 'Language de dev'}
                    - { property: 'framework', label: 'Framework'}
                    - { property: 'cms', label: 'CMS'}
                    - { property: 'technicalChallenges', label: 'Challenge technique'}
                    - { property: 'focalPoints', label: 'Point focal'}
                    - { property: 'customer', label: 'Client'}
                    - { property: 'color', label: 'Couleurs'}
                    - { property: 'country', label: 'Pays du Site'}
                    - { property: 'technology', label: 'Technologies'}
                    - { type: 'group', css_class: 'col-sm-3', label: 'Social', icon: 'user' }
                    - { property: 'viewNumber', label: 'Nombre de vue'}
                    - { property: 'likeNumber', label: 'Nombre de like'}
                    - { property: 'averageGrade', label: 'Note moyenne'}
                    - { property: 'averageJuryGrade', label: 'Note moyenne du jury'}
                    - { property: 'categoryAwards', label: 'Catégorie de prix'}
        Colors:
            class: BackBundle\Entity\Colors
            list:
                title: "Les Couleurs"
                fields:
                     - { property: 'label', label: 'Libelle'}
                     - { property: 'hexa', label: 'Hexadecimal'}
                actions:
                    - { name: 'new', label: 'Ajouter une couleur' }
            form:
                title: "Ajouter une couleur"
                fields:
                    - { property: 'label', label: 'Titre', css_class: 'col-sm-4'}
                    - { property: 'hexa', label: 'Hexa', css_class: 'col-sm-4'}
        Technologies:
            class: BackBundle\Entity\Technologies
            list:
                title: "Les Technos"
                fields:
                     - { property: 'label', label: 'Libelle'}
                actions:
                    - { name: 'new', label: 'Ajouter une techno' }
            form:
                title: "Ajouter une techno"
                fields:
                    - { property: 'label', label: 'Titre', css_class: 'col-sm-4'}
        Country:
            class: BackBundle\Entity\Country
            list:
                title: "Les Pays"
                fields:
                     - { property: 'label', label: 'Libelle'}
                actions:
                    - { name: 'new', label: 'Ajouter un pays' }
            form:
                title: "Ajouter un pays"
                fields:
                    - { property: 'label', label: 'Titre', css_class: 'col-sm-4'}
        User:
            class: UserBundle\Entity\User
            list:
                title: "Les Utilisateurs"
                actions:
                    - { name: 'new', label: 'Ajouter un Utilisateur' }
            form:
                title: "Ajouter un nouvelle utilisateur"
        VoteCriteria:
            class: BackBundle\Entity\VoteCriteria
            list:
                title: "Les Critères de Votes"
                actions:
                    - { name: 'new', label: 'Ajouter un Critère'}
            form:
                title: "Ajouter un Critère"
                fields:
                    - { property: 'name', label: 'Titre', css_class: 'col-sm-4'}
                    - { property: 'color', label: 'Couleur', css_class: 'col-sm-4'}
                    - { property: 'categoryAwards', label: 'Catégorie de Prix', css_class: 'col-sm-4'}

    design:
        form_theme: 'vertical'
        brand_color: 'grey'
        color_scheme: 'light'
        assets:
            favicon: '../docs/favicon.png'
        menu:
            - { entity: 'Agency', label: 'Agences', icon: 'anchor'}
            - { entity: 'Blog', label: 'Blog', icon: 'pencil'}
            - label: 'Les Prix'
            - { entity: 'Awards', label: 'Prix', icon: 'trophy'}
            - { entity: 'CategoryAwards', label: 'Catégorie de Prix', icon: 'certificate'}
            - { entity: 'VoteCriteria', label: 'Critères de Votes', icon: 'star'}
            - label: 'Outils'
            - { entity: 'Parameter', label: 'Paramètres', icon: 'cog'}
            - label: 'Site internet'
            - { entity: 'Project', label: 'Projet', icon: 'suitcase'}
            - { entity: 'Colors', label: 'Couleurs', icon: 'paint-brush'}
            - { entity: 'Technologies', label: 'Technos', icon: 'wrench'}
            - { entity: 'Country', label: 'Pays', icon: 'globe'}
            - label: 'Personnes'
            - { entity: 'User', label: 'Utilisateurs', icon: 'user'}
            - { entity: 'Customer', label: 'Clients', icon: 'address-book'}
