back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /administration
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

