# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /administration


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check

agency:
    type:   rest
    resource:   BackBundle\Controller\AgencyController