<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'submit_listener' shared service.

return $this->services['submit_listener'] = new \BackBundle\EventListener\SubmitListener();
