<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP98te3i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP98te3i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP98te3i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP98te3i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP98te3i\appDevDebugProjectContainer(array(
    'container.build_hash' => 'P98te3i',
    'container.build_id' => '576b1642',
    'container.build_time' => 1518767902,
));
